stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/nginx-demo"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main

update_manifest:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache yq git
  script:
    - yq -i ".spec.template.spec.containers[0].image = \"$IMAGE_NAME:$IMAGE_TAG\"" $K8S_MANIFEST_PATH
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git add $K8S_MANIFEST_PATH
    - git commit -m "Update image to $IMAGE_TAG"
    - git push "https://$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD@gitlab.com/$CI_PROJECT_PATH.git" HEAD:main
  only:
    - main
